#!/bin/bash

#zero
zero=0
##all made by me, not that shit AI!if u doubt, u can ask me(even that output, maybe it looks by generated by AI, but it's made by me.)

printf "======CPU USAGE======\n"
#cpu usage
cpu_usage="$(vmstat -t 1 2 | tail -n 1 | awk '{print 100 - $15}')"
echo "CPU usage is: $cpu_usage%."

printf "========MEM USAGE======\n"
#memory usage(used)
used_memory_ram="$(free -m | head -n 2 | awk '{print $3}' | tail -n 1)"
printf "Used memory is: $used_memory_ram Mb.\n"

#memory usage(free)
free_memory_ram="$(free -m | head -n 2 | awk '{print $4}' | tail -n 1)"
printf "Free memory is: $free_memory_ram Mb.\n"

#total memory ram
total_memory_ram="$(free -m | head -n 2 | awk '{print $2}' | tail -n 1)"
printf "Total memory is: $total_memory_ram Mb.\n"

#procentage for free memory from total memory
procentaj_free="$(echo "(($free_memory_ram / $total_memory_ram))" | bc -l | cut -c1-4)"
procentaj_final_free="$zero$procentaj_free"
echo "Free / Total is: $procentaj_final_free%."

#procentage for used memory from total memory
procentaj_used="$(echo "(($used_memory_ram / $total_memory_ram))" | bc -l | cut -c1-4)"
procentaj_final_used="$zero$procentaj_used"
echo "Used / Total is: $procentaj_final_used%."

printf "======DISK USAGE======\n"

#disk usage(all)
total_memory_disk="$(df -h | tail -n 2 | head -n 1 | awk '{print $2'})"
printf "Total disk memory is: $total_memory_disk.\n"

#disk usage(used)
used_memory_disk="$(df -h | tail -n 2 | head -n 1 | awk '{print $3'})"
printf "Used disk memory is: $used_memory_disk.\n"

#disk usage(free)
free_memory_disk="$(df -h | tail -n 2 | head -n 1 | awk '{print $4'})"
printf "Free disk memory is: $free_memory_disk.\n"

#procnetage for free disk memory
procentaj_free_disk="$(echo "(($free_memory_disk / $total_memory_disk))" | bc -l | cut -c1-4)"
procentaj_final_free_disk="$zero$procentaj_free_disk"
echo "Free / Total is: $procentaj_final_free_disk%."

#procentage for used disk memory
procentaj_used_disk="$(echo "(($used_memory_disk / $total_memory_disk))" | bc -l | cut -c1-4)"
procentaj_final_used_disk="$zero$procentaj_used_disk"
echo "Free / Total is: $procentaj_final_used_disk%."

printf "======TOP 5 PROCESSES BY CPU======\n"
#TOP 5 processes by CPU usage
echo "$(ps aux --sort=-%cpu | head -n 6)"

printf "====== TOP 5 PROCESSES BY RAM======\n"
#TOP 5 processes by MEMORY usage
echo "$(ps aux --sort=-%mem | head -n 6)"
